# # # # # # # # # # # # # # #
# SMP TWEAKS  CONFIGURATION #
# # # # # # # # # # # # # # #


# #   MAINTENANCE  MODE   # #
locked: false


# Contents of the server browser
motd:
  # Use custom MOTD
  enable: true

  # If true, a message will be picked randomly from the pool
  randomize: true

  # Set MOTD contents here.
  # Message or pool contents will appear behind static line 2 text
  # Maintenance text will appear as line 2 when server is locked
  line1: "§c[?.?.?] §6Server Name"
  line2: "§8>> §7"
  message: "Static MOTD"
  maintenance: "§c⚠ Temporarily closed for maintenance"
  pool:
    - "Random 1"
    - "Random 2"
    - "Random 3"
    - "Random 4"

# Header and footer of the TAB list
tab:
  enable: true
  header: "TAB Header"
  footer: "TAB Footer"

# Discord command
discord:
  enable: true
  message: "§9Join our discord!"
  link: "§7<link>"

# Invite cooldown (players must wait 24h until they may invite someone themselves)
inviteCooldown: true

# Custom world spawn
spawn:
  enable: true
  location:
    X: 0
    Y: 63
    Z: 0

# Crafting recipes
crafting:
  totemOfPreservation: true
  elytra: true

# Balancing tweaks
balancing:
  noMendingTrades: true
  noElytraSpawns: true
  noElytraRepair: true
  noElytraEnchants: true
  noShulkersInEnderchest: true

# Creeper explosions
disableCreeperBlockDamage: true