# # # # # # # # # # # # # # #
# SMP TWEAKS  CONFIGURATION #
# # # # # # # # # # # # # # #


# Contents of the server browser MOTD
motd:
  enable: true
  line1: "§c[?.?.?] §6Server Name"
  line2: "§8>> §7"
  appendix: "Server MOTD"

# Header and footer of the TAB list
tab:
  enable: true
  header: "TAB Header"
  footer: "TAB Footer"

# Discord command
discord:
  enable: true
  message: "§9Join our discord!"
  link: "§7<link>"

# Custom world spawn
spawn:
  enable: true
  location:
    X: 0
    Y: 63
    Z: 0

# Crafting recipes
crafting:
  totemOfPreservation: true
  elytra: true

# Balancing tweaks
balancing:
  noMendingTrades: true
  noElytraSpawns: true
  noElytraRepair: true
  noElytraEnchants: true
  noShulkersInEnderchest: true

# Creeper explosions
disableCreeperBlockDamage: true